### ISSUE TITLE
sync error using gitlab repo with default branch 'main' 

### ISSUE THREAD

**Issue by breisfeld** [trilbymedia/grav-plugin-git-sync#183]
I have recently been converting my naming convention of my repos from 'master' to 'main'.

Though I have configured the 'Advanced Git Settings' in the plugin to use 'main' as the local and remote branch names, I get an error when trying to sync:

error: src refspec main does not match any. error: failed to push some refs to 'https://user:{password}@gitlab.com/user/habsbot-grav.git'

**Comment by w00fz** [comment]
Hi @breisfeld , I think your `user` is still set to master branch, you might have to manually switch the branch to main via CLI.

`git branch main -u origin/main`

**Comment by breisfeld** [comment]
Hello @w00fz, 
When I set up the repo there was no master branch at all, so I don't think this is the issue.

**Comment by w00fz** [comment]
The error suggests that the `main` branch is not match any branch in the configuration. So i believe you are not tracking it. The command above should fix that.

You can verify this if you look into `.git/config`

**Comment by breisfeld** [comment]
My config contains
```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = git@gitlab.com:user/habsbot-grav.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main
```

**Comment by w00fz** [comment]
Yeah that config looks correct. Are you able to do a `git fetch` from the user folder?

**Comment by w00fz** [comment]
Also can you check user/config/plugins/git-sync.yaml ?

**Comment by breisfeld** [comment]
`git fetch` from my local repo seems to work fine.

`git-sync.yaml` contains
 
```
...
branch: main
remote:
  name: origin
  branch: main
git:
  author: gituser
  message: '(Grav GitSync) Automatic Commit'
  name: GitSync
  email: git-sync@trilby.media
  bin: git
logging: false
```
