### ISSUE TITLE
Odd repository errors

### ISSUE THREAD

**Issue by Wartybliggens** [trilbymedia/grav-plugin-git-sync#43]
I am hoping to use this plugin to sync code changes, and avoid using FTP altogether on the shared host where I have a little site. For instance, when I make changes to theme files. My impression was that I can push to the repo, then in the GitSync plugin pull the changes (synchronize button). However this does not seem to work. Am I misunderstanding the purpose of this plugin? Is it only for syncing content like posts? 

Also in using the synchronize button I get odd errors about untracked files. At first it complained about the .gitignore file, so I temporarily removed it from the repo and added it back. But now I get this:

> # On branch master # Untracked files: # (use "git add ..." to include in what will be committed) # # accounts/ #	config/ #	data/ # plugins/ #	themes/ nothing added to commit but untracked files present (use "git add" to track)

To start I loaded the entire site onto the server, and later ran the plugin's wizard and connected to a GitHub repo. 

Maybe I'm misunderstanding the use case here.

**Comment by paulhibbitts** [comment]
Hi @Wartybliggens , indeed the purpose of the first release of the plugin is to only sync pages for simplicity sake. Also, the plugin can "auto" detect saved changes of pages within the Admin Panel, thus no need for manual syncing.

That being said, you can easily add Themes to the sync to the current version by tweaking the blueprint file of the plugin BEFORE first running.

Look in the blueprints.yaml file for the plugin (users/plugins/git-sync/blueprints.yaml), and replace the code for the 'folders' items with this:
```
    folders:
      type: selectize
      multiple: true
      size: medium
      label: Sync Folders
      classes: fancy
      default: ['pages','themes']
      options:
        pages: Pages
        themes: Themes
      validate:
        type: commalist
```

The result will be the Themes folder will now be synced as well as the pages folder. This is obviously not a full-site sync, but will support any theme changes (with a manual sync or automatically when pushed from the repo).

Please let me know if the above works ok for you.

Cheers,
Paul
ps - you can see a working example of this approach with my Course Hub skeleton, available at https://getgrav.org/downloads/skeletons
